name: Build and release Next.js web app
on: push
jobs:
 build-project:
   name: Build Next.js application
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm Install
      - name: Build static website
        run: npm run build
      
        
